spring.application.name=web-project

server.port=8080
# ===== Database Configuration =====
spring.datasource.url=jdbc:mysql://localhost:3306/web_project_db
spring.datasource.username=web_project_db
spring.datasource.password=8SExPmKba3Ek3as6
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#debug=true

ai.model.api.url=https://yunwu.ai/v1/chat/completions
ai.model.api.key=sk-VrS2XTPTfjEPVJYCIR7EKOFs6VQLgcnHLbryHNRGBdPLUyhq
server.error.whitelabel.enabled=false
spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# JWT Configuration
jwt.secret-key=f769c3cf25fc58e8d3a979f8df34e1f9b870dea6bd6c76886ba715d1e50d9fcc
jwt.expire-time=604800000

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=hls20041225
spring.data.redis.timeout=3000ms
spring.data.redis.jedis.pool.max-active=8
spring.data.redis.jedis.pool.max-wait=-1ms
spring.data.redis.jedis.pool.max-idle=8
spring.data.redis.jedis.pool.min-idle=0


